name: 'Github Action Email Bot'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout Env
      run: echo "${{ env.MAIL_HOST }} ${{ secrets.MAIL_HOST }}."

    - name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        MAIL_HOST: ${{ env.MAIL_HOST }}
        MAIL_PORT: ${{ env.MAIL_PORT }}
        MAIL_USER: ${{ env.MAIL_USER }}
        MAIL_PASS: ${{ env.MAIL_PASS }}
        MAIL_SENDER: ${{ env.MAIL_SENDER }}
        MAIL_RECEIVER: ${{ env.MAIL_RECEIVER }}
      run: |
        python3 mail.py

